### ISSUE TITLE
Getting TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Tanya312** [pytest-dev/execnet#110]
I am trying to connect python2 to python3 on another server, and execute some code on the python3 server.
However I keep getting this error.

```
r = channel.receive()
  File "/home/abc/.virtualenvs/abc/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 737, in receive
    raise self._getremoteerror() or EOFError()
execnet.gateway_base.RemoteError: Traceback (most recent call last):
  File "<string>", line 1072, in executetask
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 3033, in <module>
TypeError: a bytes-like object is required, not 'str'
```

**Comment by nicoddemus** [comment]
Hi @Tanya312,

Can you show both server and client code?

**Comment by RonnyPfannschmidt** [comment]
closing as not reproducible

the 2<>3 bridge will go away as well
