### ISSUE TITLE
Testing with Python 3.9.15 raises PytestUnraisableExceptionWarning 

### ISSUE THREAD

**Issue by mtelka** [pytest-dev/execnet#157]
```
testing/test_basics.py::TestPureChannel::test_channel_makefile_incompatmode[thread]
testing/test_basics.py::TestPureChannel::test_factory_create[thread]
testing/test_basics.py::TestPureChannel::test_factory_getitem[thread]
testing/test_basics.py::TestPureChannel::test_channel_timeouterror[thread]
  $(PYTHON_DIR)/vendor-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Channel.__del__ at 0x7fffaa8ea280>
  
  Traceback (most recent call last):
    File "$(@D)/execnet/gateway_base.py", line 613, in __del__
      self._trace("channel.__del__")
    File "$(@D)/execnet/gateway_base.py", line 572, in _trace
      self.gateway._trace(self.id, *msg)
  AttributeError: type object 'Gateway' has no attribute '_trace'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

When I test with Python 3.7.15 I see  no similar warning.

**Comment by RonnyPfannschmidt** [comment]
this is partial lexpectedas fallout of teardown

**Comment by mtelka** [comment]
I'm unable to reproduce this issue with `execnet 2.1.1` and `Python 3.9.19`.
