### ISSUE TITLE
Gateway instantly closed when connect to Jython 2.5.1

### ISSUE THREAD

**Issue by RichiMaulana** [pytest-dev/execnet#224]
### Version details
Python version: 3.8.10
Jython version: 2.5.1 (zmpython from Zimbra)
execnet version: 2.0.2

### Problem
When I try to open a gateway to Jython the makegateway API instantly throw a SyntaxError.

Then I try to ignore that and run the remote_status API, also resulting an OSError telling that the connection already closed.

### Code&error
```
Python 3.8.10 (default, Sep 19 2023, 17:33:10)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import execnet
>>> gw =  execnet.makegateway("popen//python=/opt/zimbra/bin/zmpython")
Sep 19, 2023 7:19:35 PM org.python.google.common.base.internal.Finalizer getInheritableThreadLocalsField
INFO: Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 27
    class ExecModel(metaclass=abc.ABCMeta):
                            ^
SyntaxError: mismatched input '=' expecting RPAREN
>>> gw.remote_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/execnet/gateway.py", line 90, in remote_status
    channel = self.newchannel()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/execnet/gateway_base.py", line 1097, in newchannel
    return self._channelfactory.new()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/execnet/gateway_base.py", line 875, in new
    raise OSError(f"connection already closed: {self.gateway}")
OSError: connection already closed: <Gateway id='gw0' not-receiving, thread model, 0 active channels>
>>>
```

**Comment by RichiMaulana** [comment]
Thank you for the response @RonnyPfannschmidt 

I already try older version and found that 1.5 is working perfectly.
